Update ga layers 2
TerriaJS/natmap-catalog-v8 pull request #10
Opened 2021-02-10 08:18 UTC by mwu2018

2021-02-16 03:53 UTC, steve9164 requested changes
It's a convention in NationalMap in all groups to sort items by name. At the moment the groups are sorted in the statement about your code that adds new GA items. You should reorganise these statements so that the recursive sorting happens after your modifications.

2021-02-16 04:10 UTC, mwu2018 commented
> It's a convention in NationalMap in all groups to sort items by name. At the moment the groups are sorted in the statement about your code that adds new GA items. You should reorganise these statements so that the recursive sorting happens after your modifications.

Done.

2021-02-16 04:25 UTC, mwu2018 commented
I will update existing json file in s3 bucket.

2021-02-16 04:53 UTC, mwu2018 commented
All sorted now. See https://nationalmap.dev.saas.terria.io

2021-02-19 02:44 UTC, nf-s commented
All looks good to me!

2021-02-19 02:45 UTC, nf-s commented
Are you happy for me to merge this @steve9164 ?

2021-02-19 02:48 UTC, steve9164 approved these changes

2021-02-19 02:58 UTC, merged